tail-passengers/backend

- back/back/settings.py
- makefile
- requirements.txt
- CORS 전체 허용
- makefile 명령어 추가
- `django-cors-headers` 라는 라이브러리를 사용해서 cors 문제 해결
- settings.py 에 앱과 기본적인 설정 추가
- makefile에 --detach 옵션을 제거한 `linux-debug` 명령어 추가
> Back 12 cors fix up

- .idea/dataSources.xml
- back/back/settings.py
- back/users/models.py
- back/users/views.py
- 42api로 전달된 이미지를 db에 저장
- 이미지 자동 삭제 및 변환을 위해 Users의 delete, put 메소드 오버라이딩
---
- 기존: 42api에서 받은 정보들을 직접 post
- 수정: 42api에서 받은 정도로 users 객체를 직접 생성
- win, lose는 default=0임으로 따로 설정해주지 않아도 됨
- 불러온 이미지가 정상적이지 않을 경우, 우선 None로 저장함
- 생성 후, 기존처럼 `/users/` 로 리다이렉트
- 이미지는 `login_ig.png` 로 저장됨
- DRF는 ModelViewSet에서 기본적으로 메소드들 지원
- 이를 이용해서 put( `update` 함수)와 delete( `destroy` 함수) 메소드를 오버라이딩
- 두 메소드 모두 이미지 값이 None이 아닌지 확인한 후, 삭제
- put은 새로 받은 이미지를 db에 저장한다.
---
- 다른 모델들의 메소드들을 오버라이딩 할 경우가 너무나 많음. 이에 대한 정리 필요
- 게임, 친구 요청과 관련한 url 정리 필요
- 이미지에 null을 허용할 것인가에 대해 확인 필요
- oauth에서 받아오는 정보가 정상적이지 않을 경우에 대한 오류 처리 필요
> [Back 13] save image method overriding

- .idea/dataSources.xml
- .idea/watcherTasks.xml
- back/accounts/views.py
- back/friendrequests/serializers.py
- back/friendrequests/urls.py
- back/friendrequests/views.py
- friend_requsts/ url 구현했습니다.
- DRF가 delete, patch 메소드에서 url에 pk나 pk 역할을 할 수 있는 것을 요구했지만 기존 url엔 그런 정보가 없기에 에러를 발생시켰습니다.
- 이를 body나 lookup_field를 비활성화하는 방법으로 찾아보았으나 DRF에서 지원하지 않는 것으로 확인되어 url을 수정했습니다.
- request.user에 request를 보낸 유저의 정보가 있음을 확인했습니다.
- 위 방법을 바탕으로 아래와 같이 url을 수정하고 권한을 주었습니다.
- /friend_requests/<uuid:request_id>/
- 허용 메소드: PATCH, DELETE
- 권한
- PATCH: 요청 받은 유저
- DELETE: 요청한 유저, 요청 받은 유저
- /friend_requests/<uuid:user_id>/<str:status>/
- 허용 메소드: GET
- 권한
- GET: login한 모든 유저 
- /friend_requests/
- 허용 메소드: POST
- 권한
- POST: 요청하는 유저 == 로그인한 유저
> [Back-21] make friend requests uri

- back/back/settings.py
- back/back/urls.py
- requirements.txt
- swagger, redoc를 이용해 api 명세를 자동으로 볼 수 있도록 추가했습니다.
- drf-yasg 라이브러리를 설치해서 swagger를 연동했습니다.
- url 관련 로직은 간단하게 swagger 형식의 스키마를 보내는 동작을 추가한 것입니다.
- http://localhost:8000/swagger : api 명세를 swagger로
- http://localhost:8000/redoc : api 명세를 redoc으로
> [Back-23] connect django and swagger

- back/accounts/tests.py
- back/accounts/views.py
- oauth 관련 수정했습니다.
- users/<uuid:pk>/의 view 수정했습니다.
- 원래 oauth에서 state를 검증하는 로직이 있었습니다 (state를 back에서 랜덤으로 생성한 뒤 session에 저장, 이후 비교하는 로직)
- 하지만 프론트랑 합치는 중에 cors에러가 발생했습니다.
- 해결법으로 https://api.intra.42.fr/oauth/authorize redirect하는 곳을 프론트로 옮겼습니다.
- 즉, 프론트에서도 state가 필요해서 state를 랜덤으로 생성한 뒤 .env파일로 옮겼습니다.
- users/uuid:pk/ 가 들어오면 pk에 맞는 users의 상세 정보가 나오도록 수정했습니다.
> [Back-22] update oauth env settings

- .idea/backend.iml
- .idea/misc.xml
- back/friendrequests/models.py
- back/friendrequests/tests.py
- back/friendrequests/urls.py
- back/friendrequests/views.py
1. friend_requests test 추가했습니다.
2. friend_requests 동작을 일부 수정했습니다.
- 각 ViewSet을 기준으로 테스트를 추가했습니다.
- get 메소드에 pending 부분에서 필터부분을 "pending" -> "0" 으로 수정했습니다.
- friend_requests의 enum 중 "Reject" 를 제거했습니다.
- 이미 수락한 친구 요청의 status를 바꾸지 못하도록 설정했습니다.
- 유저가 삭제될 때 잘 삭제되는지 등 다른 모델과 연동되어 움직이는 테스트도 추가하면 좋을 것 같습니다.
> [Back-24] add test for friend request

- back/accounts/tests.py
- back/accounts/urls.py
- back/accounts/views.py
- accounts/url에서 uuid 인자를 intra_id로 수정했습니다.
- 바뀐 url에 맞게 test를 수정했습니다.
- users의 상세 정보를 확인하기 위해서는 기존에는 users/user의 uuid로 조회했습니다.
- uuid다 보기 가독성의 문제도 있어서 url는 users/intra_id로 조회가 가능하도록 수정했습니다.
- accounts의 users 모델 같은 경우 uuid를 intra_id로 옮기는 과정이 수월했습니다.
- 하지만 이것을 fk로 사용하는 다른 모델들을 어떻게 해야할지 고민입니다.
> [Back-26] modify UUID url to nickname accounts app

- back/friendrequests/serializers.py
- back/friendrequests/tests.py
- back/friendrequests/urls.py
- back/friendrequests/views.py
- back/games/serializers.py
- back/games/tests.py
- back/games/urls.py
- back/games/views.py
- intra_id에 맞춰 url 수정
- serializer 필드를 uuid -> intra_id로 수정
- 수정된 url에 맞춰서 viewset 수정
- 수정 사항에 맞춰서 test 수정
---
- method: `GET`
- status: all(전체), pending(받은 요청), accepted(친구만)
- method: `POST`
- body는 변한 것이 없으나 **uuid** 대신 **intra_id** 를 받고 **내부에서 변환하도록 변경** 했습니다.
- method: `PATCH` , `DELETE`
- intra_id를 받는 방향으로 찾아보았으나 **친구 관계 자체를 특정할 pk를 요구** 하기에 intra_id를 받을 수 없습니다.
- 이에 request_id, 즉 pk를 사용하는 방향으로 구현했습니다.
- `is_exist_user`
- 주어진 key와 value로 존재하는 usre인지 탐색하는 함수
- key는 intra_id와 user_id만 받습니다.
- `get_user_from_intra_id_or_user_id`
- 주어진 id를 intra_id 필드와 uuid 필드로 탐색하는 함수
- intra_id로 먼저 탐색하고 없을 때 uuid로 탐색합니다. (DRF 지원 사이트에서도 테스트가 가능하도록 만든 기능입니다.)
- 만약 조건에 맞는 유저가 없다면 None을 반환합니다.
- `create_with_intra_id_convert_to_user_id`
- POST 동작 중 request의 body에 있는 intra_id를 user_id로 변환하여 생성하는 함수입니다.
- …
> [Back-27] change UUID to nickname games friendrequests

- .idea/.gitignore
- .idea/backend.iml
- .idea/watcherTasks.xml
- back/games/models.py
- back/games/serializers.py
- back/games/tests.py
- back/games/urls.py
- back/games/views.py
1. Join 모델 삭제
2. winner, loser -> player1, player2로 변경
3. game log 관련 api에서 User의 정보가 모두 나오도록 변경
4. player1_score, player2_score 추가
5. game log 관련 url 변경
---
- 현재, game_log들에서 Q를 사용하여 직접 필터하여 정보를 제공하고 있습니다.
- 그렇기 때문에 가운데 Join 관련 테이블이 필요치 않기에 삭제했습니다.
- 승자 패자가 아니라 플레이어 목록으로 필드와 test를 변경했습니다.
- serializers에서 `UsersSerializer` 와 `create_game_log` 함수로 정보가 모두 나오도록 변경했습니다.
- 필드를 추가했습니다.
- `validate` 함수에 음수값을 판별하는 로직을 추가했습니다.
- method: `POST`
- 비고
- 요구하는 필드가 변경된 정보에 따라 변경되었습니다.
- method: `GET`
- 비고
- 전체 게임 로그로 올라옵니다.
- 게임 시작 시간으로 내림차순 정렬됩니다.
- method: `POST`
- 비고
- 요구하는 필드가 변경된 정보에 따라 변경되었습니다.
- method: `GET`
- 비고
- 전체 게임 로그로 올라옵니다.
- 게임 시작 시간으로 내림차순 정렬됩니다.
> [Back-28] modified game logs

- back/back/asgi.py
- back/back/settings.py
- back/pong_game/consumers.py
- back/pong_game/routing.py
- requirements.txt
- ws/login/으로 접속하면 유저의 status 변경 로직 생성했습니다.
- websocket 적용함에 따라서 설정파일 추가했습니다.
- 유저의 실시간 상태를 체크 하기 위해서 websocket를 도입했습니다.
- ws/login/으로 websocket이 연결이 되면 유저의 status를 online으로 연결이 끊어지면 offline으로 변경합니다.
- [Django Channels의 튜토리얼](https://channels.readthedocs.io/en/latest/tutorial/index.html)를 참고했습니다.
- settings.py의 INSTALLED_APPS의 순서가 django app 그 다음에 Third-party apps입니다.
- 하지만 Third-party apps의 Daphne가 에러(Daphne must be listed before django.contrib.staticfiles in INSTALLED_APPS)가 발생해서 daphne 위치만 수정했습니다. 
- websocket을 처음 도입하다보니 튜토리얼의 대부분을 따라했습니다.(추후 프로젝트에 맞게 수정및 추가가 필요합니다.)
- 다만 접속한 유저의 status만 바꾸는 간단한 로직이다보니 추후 channels Layers 같은 설정을 추가가 필요합니다. 
- 관련된 테스트도 추가할 수 있으면 좋을것 같습니다.
> [Back-29] websocket for users status

- back/back/settings.py
- back/pong_game/consumers.py
- back/pong_game/routing.py
- docker-compose.yml
- requirements.txt
- channel_layers에 맞는 기본 환경 추가 했습니다.
- general_game에 대한 기본적인 웹소켓 뼈대 추가 했습니다.
- channels에 기본 제공되는 layer는 redis를 기본으로 합니다.
- 그에 맞게 redis를 docker compose에 추가, settings.py에 CHANNEL_LAYERS 세팅, requirements.txt에  channels-redis를 추가했습니다.
- 아직 게임 로직이 정해지지 않아서 기본적인 웹소켓 뼈대만 추가 했습니다.
- url로 부터 uuid인 game_id를 받아와서 channel_layer 그룹에 추가하는것 까지 했습니다.
- redis를 사용하는것에 대한 고민이 필요합니다.
- 추후 게임 로직에 따라 많은것들이 추가 되어야 합니다.
> [Back-31] create general game consumer

- back/back/settings.py
- back/back/test_settings.py
- back/pong_game/tests.py
- makefile
- make test하면 test 되도록 makefile 수정했습니다.
- socket에 대한 테스트 환경을 구축했습니다.
- test 하기전 setting의 db를 local로 수정해야하는 불편함이 있었습니다.
- mange.py test의 settings옵션을 통해 test를 할때는 test_settings.py를 참고하도록 수정했습니다.
- 이런 명령어를 조합해서 make test하면 test 되도록 make file에 명령어를 추가했습니다.
- 비동기로 consumer들이 만들어져서 테스트도 기존 model과 다르게 몇가지 수정했습니다.
- 기존 테스트랑 다른것은 [gist](https://gist.github.com/guune/c1231a2b275f1029ca8e70fcff39c06a) 참고 바랍니다.
- 단순히 비동기 테스트에 대한 뼈대를 만드는게 목적이라서 나머지 consumer에 대한 테스트 추가가 필요합니다.
> [Back-32] test case socket

- back/pong_game/consumers.py
- back/pong_game/routing.py
- general game wait 요청이 들어왔을 때 동작을 구현했습니다.
- wait_list에는 빼서 메세지를 보내는 동작을 위해 `self` 객체 자체를 집어넣었습니다.
- 이때, 같은 유저가 여러번 웹소켓 연결 요청을 하면 다른 객체로 인식 됩니다. 예를 들어 같은 세션id로 postman을 이용해 두 번 웹소켓 연결 요청을 하면 self.user는 같지만 self는 다른 객체입니다.
- 그렇기에 intra_id_list를 두어 동일한 유저가 두 번 요청하지 못하도록 하였습니다.
- 이미 접속한 유저가 아니라면 wait_list와 intra_id_list에 추가하고 `True` 를 반환합니다.
- 만약 이미 접속한 유저라면 어떠한 동작없이 `False` 를 반환합니다.
- wait_list에서 가장 앞에 있는 두 유저한테 생성된 game_id를 전송하고 wait_list, intra_id_list에서 제거한다.
- `add_wait_list` 함수 실행 후, 유효한 요청이라면 wait_list에 2명 이상인지 확인 후 `game_match` 함수를 실행합니다.
- 만약 인증이 없는 유저일 경우 바로 종료시킨다.
- 인증이 된 유저 중, 현재 wait_list와 intra_id_list에 있는 유저라면 삭제하고 종료시킨다.
- 현재 wait_list에 있는 유저가 다시 접속했을 때도 403에러를 반환합니다. 중복이라고 명시해주는 에러를 보내면 더 좋을 것 같습니다.
> [BACK-30] create-game-wait-consumer

- back/accounts/models.py
- back/accounts/urls.py
- back/accounts/views.py
- back/pong_game/tests.py
- back/test_user.json
- 게임이 진행됨에따라 2명 이상의 유저에 로그인 해서 테스트를 진행해야 합니다.
- oauth를 이용해서 로그인을 하면 불편한 경우가 있어서 테스트용 계정들을 간단한 url로 로그인 하는 기능을 추가 했습니다.
- 테스트 모델들에 한해서 간단한 url로 로그인 하는 기능을 추가 했습니다.
- is_test_user가 true인 경우에만 url로 로그인이 가능합니다.
- 이거를 나중에 필요가 없어지면 삭제를 해야합니다.
- 관련된 테스트가 필요합니다.
> [BACK-38] 테스트용 계정들을 간단한 url로 로그인 하는 기능을 추가 했습니다.

- back/pong_game/consumers.py
- back/pong_game/module/Ball.py
- back/pong_game/module/Game.py
- back/pong_game/module/GameSetValue.py
- back/pong_game/tests.py
- docs/game_socket.md
- `ACTIVE_GAMES` 를 전역 변수로 변경하여 대기방과 게임방에서 모두 `Game` 객체에 접근할 수 있도록 수정했습니다.
- `Game` 객체 생성 시, player1, 2 를 받도록 수정했습니다.
- 이에 따라 테스트를 수정했습니다.
- `ACTIVE_GAMES` 가 전역변수가 되었습니다.
- 대기방에서 메세지를 보낼 때, `ACTIVE_GAMES` 에 `game_id` 를 키로 가지는 `Game` 객체를 생성하여 저장합니다.
- 게임방 소켓 접속 시, `game_id` 를 ( 가지고 없는 게임일 때 / 게임이 대기 중이 아닐 때 / player1 일 때 / player2 일 때 / 둘 다 아닐 때 ) 로 구분하여 처리합니다.
- 소켓 종료 시, loop를 종료하고 `ACTIVE_GAMES` 에서 제거합니다.
- 게임방 관련 로직을 확인하는 테스트 앞에 대기방에 접속하여 유효한 `game_id` 를 받는 로직을 추가했습니다.
> [Back-36] exception handling in game socket

- back/pong_game/consumers.py
- back/pong_game/module/Ball.py
- back/pong_game/module/Game.py
- back/pong_game/module/GameSetValue.py
- back/pong_game/module/Paddle.py
- back/pong_game/tests.py
- 게임 정상 종료 시 db 저장 기능을 추가했습니다.
- 2p 패들이 키입력과 반대로 움직이는 버그 수정했습니다.
- DB 저장 기능과 관련된 test를 추가했습니다.
- 게임이 정상 종료 후 db 저장에 성공 했을 때 ＂message_type＂: ＂complete＂, 실패 했을때 message_type＂: ＂error＂를 프론트에 보내줍니다.
- general_game_log에는 시작 소요 시간과 종료 소요 시간이 필요해서 Game 모델에 start_time, end_time 변수, 관련된 get, set 메서드를 추가했습니다.
- 1p, 2p 패들이 같은 로직으로 되어 있어서 move_handler 메서드에 player_num: int으로 1p, 2p를 받도록 수정했습니다.
- 정상적으로 종료 시 db 저장 관련해서 test를 추가했습니다.
- 패들이 움직이지 않은 상태로 게임이 진행되면 끝나지 않기 때문에 1p 패들을 왼쪽으로 이동시키면서 게임을 시작했습니다.
- 원래 공 속도로 진행하면 테스트하는데 너무 오래 걸려서 테스트 할 때만 공 속도를 50배로 증가시켰습니다.
- 게임 데이터가 저장되는 것과 그것을 확인하는 테스트가 동기적으로 실행 되지 않기 때문에 2초의 타임아웃을 가지고 0.2초씩 polling 방식으로 게임 데이터가 저장되는지 확인합니다.
- db 저장 종료 시 성공, 실패에 대한 메시지를 프론트에 보내주는데 그것을 처리하는 로직를 프론트에 구현 해야 합니다.
- 수정했습니다 상에는 게임 로직이 잘 표현 되는데 따로 데이터를 뽑아 봤을 때 player 1의 위치를 -로 지정해놨는데 …
> [Back-39] save game result

- back/pong_game/module/Ball.py
- back/pong_game/module/Game.py
- back/pong_game/module/GameSetValue.py
- back/pong_game/module/Paddle.py
- back/pong_game/tests.py
- game logic을 수정했습니다.
- paddle의 _move를 리팩토링 했습니다.
- 테스트에서 중복된 로직을 setup_game_environment_before_start 함수로 만들었습니다.
- 바뀐 로직을 확인하는 테스트를 추가했습니다.
- 저희가 가정한 paddle1의 z 위치는 마이너스, paddle2의 z 위치는 플러스였습니다.
- 하지만 실제로 데이터를 뽑아보니 반대로 되어 있어서 관련된 로직을 수정했습니다.
- PADDLE_BOUNDARY 상수를 통해 조금 더 가독성 좋게 할 수 있을 것 같아서 수정했습니다.
- start 하기 전까지 wait하고, ready하는 중복되는 로직이 있어서 그 로직을 함수로 뺐습니다.
- 저희가 가정한 paddle z위치, 공 위치를 확인하는 테스트를 추가했습니다.
> [Back-41] fix pong game logic

- back/pong_game/consumers.py
- back/pong_game/module/GameSetValue.py
- back/pong_game/module/Round.py
- back/pong_game/module/Tournament.py
- back/pong_game/routing.py
- back/pong_game/tests.py
- TournamentGameWaitConsumer 구현했습니다.
- 관련된 테스트를 추가했습니다.
- Round, Tournament 클래스 뼈대를 구현했습니다.
- 토너먼트 게임의 첫 시작으로 TournamentGameWaitConsumer를 구현했습니다.
- TournamentGameWaitConsumer는 ＂ws/tournament_game/wait/＂로 접속을 하면 토너먼트 방을 생성하기 전까지 역할을 수행합니다.
- 접속을 하면 
- 1. 현재 있는 토너먼트 리스트를 클라이언트로 보냄
- 2. 클라이언트에서 원하는 토너먼트 이름과 방 생성 버튼을 누르면 토너먼트 이름 유효성을 검사해서 성공, 실패 메시지 클라이언트에게 보냄
- 유효성 검사: 현재 존재하는 토너먼트 이름을 보낼 때, 토너먼트 이름을 안 보낼 때, 금지된 토너먼트 이름을 보낼 때, db에 저장된 토너먼트 이름을 보낼 때
- 간단한 생성자만 구현했습니다.
- 1. 현재 존재하는 토너먼트 방을 잘 받아오는지 테스트
- 2. 토너먼트 이름을 consumer에게 보냈을 때 성공 또는 실패를 클라이언트에게 잘 보내는지 테스트를 추가했습니다.
- 토너먼트 구현했습니다 서로 연관이 되어 있어서 다른 컨슈머를 구현하면 다른 테스트를 더 추가해야 합니다.
- 실제로 프론트랑 결합해봐야 합니다.
> [Back-44] create tournament game wait consumer

- back/accounts/models.py
- back/accounts/serializers.py
- back/accounts/tests.py
- back/accounts/urls.py
- back/accounts/views.py
- back/friendrequests/serializers.py
- back/friendrequests/tests.py
- back/friendrequests/urls.py
- back/friendrequests/views.py
- back/games/serializers.py
- back/games/tests.py
- back/games/views.py
- back/test_user.json
- `Users` 모델의 삭제 기능을 제거했습니다.
- `Users` 모델의 `House` 필드와 그에 맞는 Enum, dict을 추가했습니다.
- `FriendRequest` 모델에서 GET 요청 시, 내가 아닌 상대방의 정보가 `friend_requests` 필드에 들어가도록 변경했습니다.
- `Game` log 들도 GET 요청 시, 모든 정보를 받도록 수정했습니다.
- 그 외에 Black formatter 적용 및 안 쓰는 라이브러리를 제거했습니다.
- `Users` 의 삭제 기능이 사용되지 않기에 제거헀습니다.
- 코알리숑을 토대로 호그와트 네 개의 기숙사 중 하나로 맵핑하여 `house` 필드에 저장했습니다.
- serializer에서 friend_request가 적용되지 않는 것을 확인했습니다.
- 이에 `request_user_id` 와 `response_user_id` 를 `UserSerializer` 로 필드를 변경해서 `Users` 전체 필드가 보이도록 변경했습니다.
- 그리고 view에서 자신이 아닌 유저의 정보만 남기고 `friend_requests` 필드에 저장되도록 구현했습니다.
- `player1_user` , `player2_user` 가 제대로 적용되지 않는 것을 확인했습니다.
- 위와 마찬가지로 `player1` , `player2` 를 `UserSerializer` 로 필드를 변경해서 `Users` 전체 필드가 보이도록 변경했습니다.
- 모델의 변경에 맞춰서 test를 변경 및 제거했습니다.
- 현재 제 로컬에서 아래와 같은 에러가 발생합니다. 수정해야 개발이 원활할 것 …
> [Back-47] update api

- back/accounts/views.py
- 프로필 이미지 관련 변경 에러 추가했습니다.
- db를 직접 건드려서 파일을 삭제하는 것은 고려하지 않았습니다.
- 프로필 이미지를 db에서 임의로 삭제해도 db에 이미지 주소는 남아있습니다.
- 이것이 나중에 이미지를 변경하면서 이전 이미지를 삭제할 때 에러를 발생시킵니다.
- 그래서 pass로 넘어가도록 만들었습니다.
> [Back-48] create user profile image error handler

- back/pong_game/consumers.py
- back/pong_game/module/GameSetValue.py
- back/pong_game/module/Paddle.py
- back/pong_game/module/Player.py
- back/pong_game/module/Round.py
- back/pong_game/module/Tournament.py
- back/pong_game/routing.py
- back/pong_game/tests.py
- docs/tournament_game_socket.md
- makefile
- #42 에 맞혀서 테스트를 구현했습니다.
- 테스트를 구현하면서 생긴 에러, 버그들을 수정했습니다.
- 토너먼트 게임에서 프론트가 요구한 사항을 추가했습니다.
- `TournamentGameRoundConsumerTests` 클래스를 만들고 그 클래스 내부에 `test_round_logic_test()` 함수를 추가했습니다.
- `_test_user(), delete_test_user(), get_user()`
- 유저를 생성, 삭제, 조회하는 함수입니다.
- `wait_for_tournament_data(),  get_tournament_data()`
- 토너먼트의 데이터를 가져오는 함수로써 최대 1초까지 polling 형식으로 토너먼트 데이터를 가져옵니다.
- `setUp()`
-  가짜 토너먼트 데이터를 ACTIVE_TOURNAMENTS에 주입합니다.
- `connect_and_echo_data()`
- 연결하고 받은 메시지를 그대로 다시 보내는 함수입니다.
- 토너먼트를 대기, 라운드를 두 단계로 나누면 대기에서 쓰이는 함수입니다.
- `connect_and_send_ready_data()`
- 연결하고 매개변수로 받은 ready_data를 보내는 함수입니다.
- 라운드 단계에서 쓰이는 함수입니다.
- `discard_all_message()`
- 작성한 consumer 들은 receive를 받고 토너먼트나 플레이어 상태를 변경시킵니다.
- 아직 receive를 덜 한 것들이 있으면 receive를 하는 함수입니다.
- `perform_test_sequence(), …
> [Back-50] create tournament game round consumer test

- back/accounts/models.py
- back/accounts/tests.py
- back/accounts/urls.py
- back/accounts/views.py
- back/back/settings.py
- back/pong_game/consumers.py
- back/pong_game/module/GeneralGame.py
- back/pong_game/module/Tournament.py
- back/pong_game/tests.py
- makefile
- 하드 코딩된 주소 env에서 받아오도록 수정했습니다.
- login, log out 시 user.is_active 상태 변경 기능 추가했습니다.
- 게임 승패시 유저 데이터 db 업데이트 기능 추가했습니다.
- 관련된 테스트 추가했습니다.
- 하드 코딩된 https://127.0.0.1/를 env에 있는 BASE_IP를 받아와서 redirect 하도록 수정했습니다.
- 나중에 remote 모듈 할 때 도움될 것 같습니다.
- 프론트에서 patch로 요청하는 게 아닌 login 하면 알아서 바뀌도록 수정해달라고 해서 기능을 추가했습니다.
- login 할 때만 True로 변경하도록 했습니다.
- GameSetValue에서 MAX_SCORE를 가져와서 이 점수랑 일치하는 플레이어 아이디를 winner_id, 아닌 플레이어 아이디는 loser_id로 반환하게 했습니다.
- 둘 다 MAX_SCORE에 도달하지 못한 경우는 에러라 생각해 None을 반환하게 했습니다.
- 1의 get_winner_loser_intra_id(self)랑 비슷한 함수로서 round_number에 맞는 winner_id, loser_id를 반환합니다
- F() log out 시 데이터베이스 레벨에서 수행돼서 레이스 컨디션 문제를 방지할 수 있다고 해서 추가했습니다.
```
Users.objects.filter(intra_id=winner_id).update(
win_count=F(＂win_count＂) + 1
)
```
이것을 풀어쓰면
```
winner = Users.objects.get(intra_id=winner_intra_id) …
```
> [Back-53] user win loss update after game finish

- back/pong_game/consumers.py
- 토너먼트 네임이 영어가 아니여도 가능하게 수정했습니다.
- 프론트에서 테스트를 하는 중 토너먼트 네임이 영어만 가능하다는것을 알게 되었습니다.
- 다중 언어를 지원하는데 영어만 지원하는건 이상하다고 생각해서 수정했습니다.
- md5는 빠르지만 너무 빠른 속도 때문에 보안적으로 취약합니다.
- 하지만 채널네임에서 보안은 상관이 없기 때문에 가볍고 빠른 해쉬 함수인 md5를 선택했습니다.
- 게임 종료 후 채널네임이 일본어, 한국어, 20글자가 넘는 경우등 잘 저장이 되는지 테스트가 필요합니다.
- 글자 수가  tournament_name: str = models.CharField(max_length=20) 이런식으로 되어 있어서 백엔드나 프론트엔드에서 검증 로직이 필요할 것 같습니다.
> [Back-58] channel name internationalization

- back/pong_game/consumers.py
- back/pong_game/tests.py
- TournamentGameRoundConsumer 의 group_name도 hash로 수정했습니다.
- TournamentGameRoundConsumerTests를 수정했습니다.
- #49 에서 group_name을 hash함수를 사용했습니다.
- 하지만 다른 consumer에서 적용이 안 된 곳이 있어서 hash 함수를 적용했습니다.
- 기존 토너먼트 정상적 로직 테스트에서 토너먼트 네임만 "한글"로 바꿨습니다.
> [Back-59] fix channel name internationalization

- back/games/tests.py
- back/games/urls.py
- back/games/views.py
- 프론트 요청에 따라 `general_game_logs/me/` 와 `tournament_game_logs/me/` 를 구현했습니다. 
- 일반 게임과 토너먼트 게임 관련 자신의 게임 로그를 가져오는 api를 구현했습니다.
- accounts에서 만든 것과 동일하게 viewset을 새로 만들어서 구현했습니다.
- 이와 관련한 간단한 테스트도 추가했습니다.
> [Back-61] create me api

- back/accounts/views.py
- back/pong_game/consumers.py
- back/pong_game/module/GameSetValue.py
- back/pong_game/module/GeneralGame.py
- back/pong_game/module/Tournament.py
- back/pong_game/tests.py
- makefile
- `get_or_create()` 매개변수 수정했습니다.
- `PlayerStatus`를 `GameStatus`로 변경했습니다.
- 토너먼트 이름 글자 수 확인하는 로직 추가했습니다.
- `TournamentGameRoundConsumer`에서 플레이어 연결 순서와 관계없이 진행되도록 수정했습니다.
- 비정상 `disconnect`시 `TournamentStatus.ERROR`로 변경하는 로직 추가했습니다.
- 관련된 테스트 추가했습니다.
- `Oauth`로 로그인한 후 다른 브라우저에서 같은 아이디로 로그인 했을 때 `IntegrityError`가 발생했습니다.
- `get_or_create`()의 `kwargs`인자는 검색에 `defaults`인자는 생성 시 사용되므로, 이를 분리하여 명확하게 구분하였습니다.
- 게임의 상태 관리를 위해 `PlayerStatus` 대신 `GameStatus`를 도입하여, 상태 관리의 명확성과 유지 보수성을 개선했습니다.
- 게임 모델 규정에 따라 토너먼트 이름은 최대 20글자로 제한됩니다.
- 사용자가 규정을 초과하는 이름을 입력할 경우를 방지하기 위해, 이름 길이를 검증하는 로직을 추가했습니다.
- 기존 로직에서는 플레이어의 연결 순서에 따라 게임 진행에 오류가 발생할 수 있었습니다.(1221 문제)
- 모든 라운드의 플레이어가 준비 상태일 때만 게임이 시작되도록 로직을 개선했습니다.
- 라운드 consumer에서 1라운드 1p(1-1), 1-2, 2-1, 2-2 플레이어가 있을 때 1-1, 1-2, 2-1, 2-2 순서대로 connect 하는 것을 1, 1, 2, …
> [Back-55] test disconnect tournament game

- back/back/settings.py
- back/back/urls.py
- `DEBUG` 모드를 껐습니다.
- `CORS` 관련 설정을 제거했습니다.
- `media` 폴더 url을 재설정했습니다.
- production 준비가 거의 마무리 되어가기에 `DEBUG` 모드를 종료했습니다.
- 또한 `ALLOWED_HOSTS` 역시 현재 `BASE_URL` 만 허용하도록 수정했습니다.
- nginx를 middleware로 front와 back이 통합되었기 때문에 CORS 설정을 제거하였습니다.
- `DEBUG` 모드를 종료하면서 기존의 `STATIC` 은 경로로 사용할 수 없습니다.
- 그렇기에 `re_path()` 함수로 경로를 재설정 했습니다.
- `static`은 현재 없기 때문에 따로 재설정하지 않았습니다.
- 제가 확인했지만 프론트 개발자들이 통합 레포지토리에서 잘 동작하는지 확인해봐야 합니다.
> [Back-63] turn off debug mode

- back/accounts/models.py
- back/back/test_settings.py
- back/pong_game/consumers.py
- back/pong_game/module/GeneralGame.py
- back/pong_game/module/Player.py
- back/pong_game/module/Round.py
- back/pong_game/module/Tournament.py
- back/pong_game/tests.py
- docs/general_game_socket.md
- docs/tournament_game_socket.md
- 일반 게임이 끝났을 때, 두 플레이어 모두 db에 저장해서 로그가 중복되는 현상 수정
- 진행중인 게임과 인원이 꽉 찬 게임은 wait_list에서 제외해서 보내주도록 수정
- 토너먼트 start 메시지에 1p, 2p 추가
- 프론트에 보내주는 메시지에서 intra_id -> nickname으로 수정
- 게임이 시작할 때와 득점했을 때, 2초동안 공이 움직이지 않도록 수정
- db complete 메시지에 게임에 참석한 인원 내용도 같이 전송하도록 수정
- test 모드에선 모든 host를 허용하도록 수정
- 현재 양쪽 플레이어에게 모두 end 메시지를 받고 db에 저장하는 로직을 수행합니다. 이에 db에 두 번 저장합니다.
- 이를 방지하기 위해 승자의 intra_id만 db 저장 로직을 수행하도록 변경했습니다.
- 또한 승자가 여러번 저장 요청하는 것을 방지하기 위해 `db_complete` 라는 boolean 값을 추가했습니다.
- 프론트에서 이미 진행 중인 게임과 인원이 꽉 찬 게임을 제거해달라는 요청을 수용했습니다.
- `_get_wait_list()` 함수를 만들어서 관련된 로직을 수행하도록 만들었습니다.
- 프론트 요청에 따라 토너먼트 start 메시지에 1p, 2p를 추가했습니다.
- intra_id는 불변하고 nickname만 변경이 가능합니다. 그래서 표시해야 할 이름도 intra_id가 아니라 nickname이 맞다고 판단했습니다.
- 프론트와 합의 후, 필드명도 nickname으로 변경하고 보내는 값들도 nickname으로 변경했습니다.
- 프론트 요청에 따라 공이 2초 간 정지되는 …
> [Back-64] fixed game error

- back/accounts/views.py
- back/pong_game/consumers.py
- makefile
- TODO문을 확인 후, 제거했습니다.
- loop task를 종료하는 과정에서 예외처리를 수정했습니다.
- login 관련 예외처리를 수정했습니다.
- 대부분의 TODO문이 동작과 관계없는 것으로 확인했습니다. 그래서 제거했습니다.
- debug용 post는 주석처리만 해서 test가 필요할 때, 다시 사용할 수 있도록 만들었습니다.
- 현재 일반 게임에서 loop task에 대한 예외 처리가 없습니다. 그리고 if문으로 검증하는 것이 비동기에서 위험이 있을 것으로 간주했습니다.
- 이에 try, except문에 추가하는 것으로 예외 처리를 진행했습니다.
- 만약 다른 42 캠퍼스나 키값이 변경되면 login에서 에러가 발생합니다.
- 그래서 키값을 가져오는 동작에서 try, except으로 묶고 에러가 발생하면 홈페이지로 redirect 시켰습니다.
- 현재 `pong_game.tests.TournamentGameRoundConsumerTests.test_disconnect` 에서 에러가 발생했다 안 했다가 합니다. 통합 레포에선 발생하지 않지만 주시 할 필요는 있어 보입니다.
> [Back-65] solve TODO

- back/back/settings.py
- back/pong_game/consumers.py
- back/pong_game/tests.py
- api의 기본 render 방식으로 json으로 변경했습니다.
- 토너먼트 대기 중, 연결 종료 시 중복 종료되는 동작을 수정했습니다.
- 장고에 설정된 기본 render 방법은 http 방식입니다.
- 이를 42api와 같은 방식인 json 방식으로 수정했습니다.
- 토너먼트 대기 중 나갈 시, `self.tournament.disconnect_tournament(self.user.nickname)` 함수가 두 번 호출됩니다.
- 이때 문제는 `self.tournament.disconnect_tournament(self.user.nickname)` 함수가 전체 인원을 줄이는 동작이 포함되어 있기에 두 명이 나간 것처럼 동작됩니다.
- 이에 data를 한 번 받고 이를 두 그룹에 전송하는 것으로 수정했습니다.
> Back 71 combine with submitted
